#!/usr/bin/env python3
"""Mirror assessment due dates into timetable/deadlines/ as all-day Full Calendar notes.

The assessment notes in projects/*/assessments/ stay the only source of truth. This folder is
generated: every run deletes and rewrites it, so never edit these notes by hand.

Show them in Obsidian by adding a Full Calendar "Full Note" calendar for the folder timetable/deadlines
(setup-obsidian does this). Without the plugin the notes are harmless. Assessments with a blank `due`
(predicted hand-ins, undated exams) and ones already Submitted or Marked are left out.

Usage:  python3 sync_deadlines.py [<vault>]     (default: the current folder)
"""
import re
import sys
from pathlib import Path

VAULT = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
OUT = VAULT / "timetable" / "deadlines"
SKIP_STATUS = {"Submitted", "Marked"}


def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---", text, re.S)
    props = {}
    if m:
        for line in m.group(1).splitlines():
            k, sep, v = line.partition(":")
            if sep and not line.startswith(" "):
                props[k.strip()] = v.strip().strip('"')
    return props


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.md"):
        old.unlink()

    count = 0
    for note in sorted(VAULT.glob("projects/*/assessments/*.md")):
        if note.parts[-3].startswith(("EXAMPLE-", "_template")):
            continue
        p = frontmatter(note.read_text())
        due = p.get("due", "")
        if p.get("kind") != "assessment" or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", due):
            continue
        if p.get("status") in SKIP_STATUS:
            continue
        time = p.get("due_time", "")
        title = f"{'⏰ ' + time + ' ' if time else '⏰ '}{p.get('code', '')} {p.get('item', note.stem)}"
        title = title.replace('"', "'")
        rel = f"../../{note.relative_to(VAULT).as_posix()}"
        lines = [
            "---",
            f'title: "{title}"',
            "allDay: true",
            "type: single",
            f"date: {due}",
            "---",
            f"Deadline mirrored from [{note.stem}]({rel}) ({p.get('type', '')}, {p.get('weight') or '–'}%, "
            f"status: {p.get('status', '')}).",
            "",
            "Generated by `sync_deadlines.py` (create-study-timetable skill). Edit the assessment note, not this one.",
            "",
        ]
        (OUT / f"due-{note.stem}.md").write_text("\n".join(lines))
        count += 1
    print(f"Wrote {count} deadline note{'' if count == 1 else 's'} to {OUT.relative_to(VAULT)}")


if __name__ == "__main__":
    main()
